#!/bin/bash
set -e

# This script downloads a file from Google Drive using gdown.

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <file_id>"
    exit 1
fi

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
ID=$1

venvDir=$SCRIPT_DIR/.gdown

# Create a virtual environment if it doesn't exist
if [ ! -d "$venvDir" ]; then
    python3 -m venv $venvDir
    . $venvDir/bin/activate
    pip install gdown
else
    . $venvDir/bin/activate
fi

echo "Downloading file with id $ID"
python3 -c "import gdown; gdown.download(id='$ID', quiet=False)"